SELECT USER_ID, AGE_GROUP, LOCATION, DEVICE_TYPE, SUBSCRIPTION_TYPE, DAYS_SINCE_REGISTRATION, 
TOTAL_PURCHASES, AVG_ORDER_VALUE, LAST_PURCHASE_DAYS, SESSIONS_LAST_30_DAYS, TIME_ON_SITE_MINUTES, 
PAGES_PER_SESSION, CART_ABANDONMENT_RATE, PURCHASE_FREQUENCY, TOTAL_PURCHASES_PER_DAY, 
DAYS_BETWEEN_FIRST_AND_LAST_PURCHASE, BUCKET_AVG_ORDER_VALUE 
FROM public.users_promociones 
WHERE DATE(DATETIME) =  CURRENT_DATE()
AND USER_ID NOT IN (SELECT USER_ID FROM public.users_promociones);